config/routes.rb
require 'silencer'

ChaosRails::Application.routes.draw do
  devise_for :users

  use_doorkeeper
  use_doorkeeper_openid_connect

  root to: 'static#home'

  match '*path', to: 'application#options', via: :options

  resources :shows,       only: [:index, :show]
  resources :workshops,   only: [:index, :show]
  resources :news,        only: [:index, :show]
  resources :venues,      only: [:index, :show]
  resources :seasons,     only: [:index, :show]

  resources :membership_activation_tokens, only: [] do
    member do
      get 'activate', to: 'membership_activation_tokens#activate'
      put 'submit', to: 'membership_activation_tokens#submit'
      patch 'submit', to: 'membership_activation_tokens#submit'
    end
  end

  resources :users, only: [:show] do
    collection do
      get 'current', to: 'users#current'
    end
  end

  get 'marketing_creatives/sign_up', to: 'admin/marketing_creatives/profiles#sign_up'

  COMPLAINTS_ALIASES.each do |path|
    get path, to: redirect('complaints/new')
  end

  resources :complaints, only: [:new, :create]

  get 'attachments/:slug(/:style)', to: 'attachments#file', as: 'attachment'

  namespace :admin do
    get '', to: 'dashboard#index'

    get 'resources', to: 'resources#page', as: :resources_index
    get 'resources/membership_checker', to: 'resources#membership_checker', as: :resources_membership_checker
    get 'resources/(*page)', to: 'resources#page', as: :resources

    get 'answer/:id/file', to: 'answers#get_file', as: :answer_get_file

    resources :events, only: [:index, :show] do
      member do
        get 'xts', to: 'events#find_by_xts_id'
      end
    end

    resources :shows do
      resources :feedbacks, except: [:show]

      collection do
        get 'query_xts'
      end

      member do
        post 'create_staffing_debts', to: 'shows#create_staffing_debts'
        post 'create_maintenance_debts', to: 'shows#create_maintenance_debts'
        get 'xts_report'
        post 'convert_to_season', to: 'shows#convert_to_season'
        post 'convert_to_workshop', to: 'shows#convert_to_workshop'
      end
    end

    resources :workshops

    resources :debt_notifications, only: [:index]

    resources :staffing_debts do
      member do
        put 'assign'
        put 'unassign'
      end
    end

    resources :maintenance_debts do
      member do
        put 'convert_to_staffing_debt'
      end
    end

    resources :debts

    resources :venues
    resources :seasons
    resources :news
    resources :fault_reports

    resources :event_tags
    resources :attachment_tags
    resources :picture_tags

    resources :attachments, only: [:index]
    resources :pictures, only: [:index]

    resources :opportunities do
      member do
        put 'approve'
        put 'reject'
      end
    end

    resources :membership, only: [] do
      collection do
        get 'check_membership', to: 'membership#check_membership'
      end
    end

    resources :editable_blocks
    resources :mass_mails

    resources :users do
      member do
        post 'reset_password'
      end

      collection do
        get  'autocomplete_list', constraints: { format: :json }
      end
    end

    resources :membership_activation_tokens, only: [:new] do
      collection do
        post 'create_activation', to: 'membership_activation_tokens#create_activation'
        post 'create_reactivation', to: 'membership_activation_tokens#create_reactivation'
      end
    end

    resources :roles do
      member do
        post 'add_user', to: 'roles#add_user'
        delete 'purge', to: 'roles#purge'
      end
    end

    get  '/permissions/grid', to: 'permissions#grid', as: :permissions
    post '/permissions/grid', to: 'permissions#update_grid', as: :update_permissions

    resources :techies do
      collection do
        get 'tree'
      end
    end

    get 'techie_families', to: 'techies#index'

    namespace :marketing_creatives do
      resources :profiles do
        collection do
          get 'sign_up', to: 'profiles#sign_up'
        end

        member do
          put 'approve'
          put 'reject'
        end
      end

      resources '', controller: 'categories', as: 'categories'
    end

    resources :staffing_templates

    resources :staffings do
      collection do
        get ':slug/grid', to: 'staffings#grid', format: :html, as: :grid
        get 'guidelines'
      end
    end

    match '/staffings/job/:id/sign_up_confirm', to: 'staffings#sign_up_confirm', via: [:get, :put], as: :sign_up_confirm
    put '/staffings/job/:id/sign_up', to: 'staffings#sign_up', as: :staffing_sign_up

    get '/proposals', to: redirect('/admin/proposals/calls')
    namespace :proposals do
      resources :calls do
        member do
          put 'archive'
        end

        resources :proposals, only: :index
      end

      resources :proposals, except: :index do
        member do
          put 'approve'
          put 'reject'
          put 'convert'
        end
      end

      get '/about', to: 'proposals#about'
      resources :call_question_templates
    end

    namespace :questionnaires do
      resources :questionnaires do
        member do
          get  'answer', to: 'questionnaires#answer'
          put 'answer', to: 'questionnaires#set_answers'
          patch 'answer', to: 'questionnaires#set_answers'
        end
      end

      resources :questionnaire_templates
    end

    resources :complaints, except: [:new, :create] do
      get 'new', to: redirect('/complaints/new')
    end

    get '/reports/', to: 'reports#index', as: 'reports'
    namespace 'reports' do
      %w(roles members newsletter_subscribers staffing).each do |action|
        put action, action: action, as: action
      end
    end

    namespace 'jobs' do
      %w(overview working pending failed remove retry).each do |action|
        get action, action: action, as:  action, controller: '/admin/job_control'
      end
    end

    namespace 'help' do
      %w(kramdown venue_location).each do |action|
        get action, action: action, as:  action, controller: '/admin/help'
      end
    end

    get 'committee', to: 'static#committee', as: :committee

    if Rails.env.test? || Rails.env.development?
      get 'dashboard/widget/:widget_name', to: 'dashboard#widget'
    end
  end

  get 'archives', to: 'archives#index', as: :archives_index
  namespace :archives do
    get 'events', to: 'events#index', as: :events
    get 'shows', to: 'shows#index', as: :shows
    get 'workshops', to: 'workshops#index', as: :workshops
    get 'proposals', to: 'proposals#index', as: :proposals
  end

  post 'markdown/preview', to: 'markdown#preview'

  get 'about', to: 'about#page', as: :about_index
  get 'about/(*page)', to: 'about#page', as: :about

  get 'get_involved', to: 'get_involved#page', as: :get_involved_index
  get 'get_involved/opportunities', to: 'get_involved#opportunities', as: :get_involved_opportunities
  get 'get_involved/(*page)', to: 'get_involved#page', as: :get_involved

  get 'youth', to: redirect('/getinvolved/youth_project')

  get 'welcomeweek', to: redirect('/welcome_week')
  get 'welcome_week/parapicnic_in_the_park', to: redirect('https://theatreparadok.co.uk/events/2021_09_parapicnic/')
  get 'welcome_week/catching_up', to: redirect('https://theatreparadok.co.uk/events/catching-up-fringe-show-performance-screening-for-welcome-week/')

  get 'welcome_week', to: redirect('get_involved/welcome_week')

  get '/:id', to: 'seasons#show', constraints: Constraints::ExistingSeason.new

  get '/*page', to: 'static#show', as: :static, constraints: lambda { |request|
    !request.path.starts_with?('/rails/active_storage') && !request.path.starts_with?('/assets')
  }

end

app/models/event.rb
##
# Probably the most important model in the app.
#
# Note that urls are generated to include the slug rather than the id of an event.
# Therefore, all lookups must be done as follows:
#  @event = Event.find_by_slug(params[:id])
#
# == Schema Information
#
# Table name: events
#
# *id*::                     <tt>integer, not null, primary key</tt>
# *name*::                   <tt>string(255)</tt>
# *tagline*::                <tt>string(255)</tt>
# *slug*::                   <tt>string(255)</tt>
# *publicity_text*::         <tt>text(65535)</tt>
# *members_only_text*::      <tt>text(65535)</tt>
# *xts_id*::                 <tt>integer</tt>
# *created_at*::             <tt>datetime, not null</tt>
# *updated_at*::             <tt>datetime, not null</tt>
# *is_public*::              <tt>boolean</tt>
# *image_file_name*::        <tt>string(255)</tt>
# *image_content_type*::     <tt>string(255)</tt>
# *image_file_size*::        <tt>integer</tt>
# *image_updated_at*::       <tt>datetime</tt>
# *start_date*::             <tt>date</tt>
# *end_date*::               <tt>date</tt>
# *venue_id*::               <tt>integer</tt>
# *season_id*::              <tt>integer</tt>
# *author*::                 <tt>string(255)</tt>
# *type*::                   <tt>string(255)</tt>
# *price*::                  <tt>string(255)</tt>
# *spark_seat_slug*::        <tt>string(255)</tt>
# *maintenance_debt_start*:: <tt>date</tt>
# *staffing_debt_start*::    <tt>date</tt>
# *proposal_id*::            <tt>integer</tt>
#--
# == Schema Information End
#++

class Event < ApplicationRecord
  include TimeHelper
  include ApplicationHelper
  include AttachmentItem
  include VideoLinkItem
  include MdHelper

  resourcify

  # Use the format slug for urls. e.g. /events/myshow
  def to_param
    slug
  end

  # Validations #
  validates :name, :slug, :publicity_text, :members_only_text, :start_date, :end_date, presence: true

  # Relationships #

  belongs_to :proposal, class_name: 'Admin::Proposals::Proposal', optional: true

  has_many :team_members, -> { includes(:user) }, class_name: '::TeamMember', as: :teamwork, dependent: :destroy
  has_many :users, through: :team_members
  has_many :pictures, -> { includes(:picture_tags, :picture_tags_pictures, { image_attachment: :blob} ) }, as: :gallery, dependent: :restrict_with_error
  has_many :questionnaires, class_name: 'Admin::Questionnaires::Questionnaire', dependent: :restrict_with_error

  belongs_to :venue
  belongs_to :season, optional: true

  has_and_belongs_to_many :event_tags, optional: true

  accepts_nested_attributes_for :team_members, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :pictures, reject_if: :all_blank, allow_destroy: true

  # ActiveStorage #
  has_one_attached :image

  validates :image, content_type: %i[png jpg jpeg gif]

  # Scopes #

  scope :current, -> { where(['end_date >= ? AND is_public = ?', Date.current, true]) }
  scope :future, -> { where(['end_date >= ?', Date.current]) }
  scope :this_year, -> { where('end_date >= ?', ApplicationController.helpers.start_of_year).where('start_date < ?', ApplicationController.helpers.next_year_start) }

  # ONLY LOOKS AT DAY AND MONTH! NOT AT YEAR.
  # Excludes shows that go into a new year (imps, candlewasters, the old ones we only know the year off, etc) because complicated logic and it wasn't very relevant.
  scope :on_date, ->(date) { where('(MONTH(start_date) < :month OR (MONTH(start_date) = :month AND DAY(start_date) <= :day)) AND (MONTH(end_date) > :month OR (MONTH(end_date) = :month AND DAY(END_DATE) >= :day))', { day: date.day, month: date.month}) }

  # Events are generally ordered with the most recent/upcoming ones first.
  default_scope -> { order('end_date DESC') }

  # Callbacks
  after_initialize :set_default_members_only_text

  # Returns the last event to have finished.
  def self.last_event
    return reorder('end_date DESC').where(['end_date < ? AND is_public = ?', Date.current, true]).first
  end

  # Formats the shows so they can be used in a selection field
  def self.selection_collection
    return pluck(:name, :id)
  end

  ##
  # Generates a default image for the event. If extra artwork is added, increase the base of the modulo call.
  #
  # NOTE: The first image must have filename 0.png - remember that in modulo 4 (for example), valid numbers are 0,1,2,3 (not 4)!
  ##
  def fetch_image
    number = id.modulo(4)
    image.attach(ApplicationController.helpers.default_image_blob("events/#{number}.png")) unless image.attached? 

    return image
  end

  ##
  # Returns the url of the slideshow image
  ##
  def thumb_image_url
    return Rails.application.routes.url_helpers.rails_representation_url(fetch_image.variant(ApplicationController.helpers.slideshow_variant).processed, only_path: true)
  end

  ##
  # Returns the url of the slideshow image
  ##
  def slideshow_image_url
    return Rails.application.routes.url_helpers.rails_representation_url(fetch_image.variant(ApplicationController.helpers.slideshow_variant).processed, only_path: true)
  end

  ##
  # Generates the frequently used "startdate - enddate" string.
  #
  # The date format used is the :long format, defined in /config/locales/en.yml
  ##
  def date_range(include_year, format = :long)
    return time_range_string(start_date, end_date, include_year, format)
  end

  def short_blurb
    (tagline.presence || truncate_markdown(publicity_text, 120)).html_safe
  end

  def simultaneous_seasons
    return Season.where('start_date <= ? and end_date >= ?', end_date, start_date)
  end

  def possible_proposals
    proposals = Admin::Proposals::Proposal.where(successful: true)

    if persisted?
      date_range = start_date.advance(years: -1)..start_date

      call_ids = Admin::Proposals::Call.where(submission_deadline: date_range).ids

      proposals = proposals.where(call_id: call_ids)

      # The attached proposal should always be included, even if it does not fall within the range or was not successful.
      proposals = proposals.or(Admin::Proposals::Proposal.where(id: proposal.id)) if proposal.present?
    end

    return proposals
  end

  def all_attachments
    answers = Admin::Answer.where(answerable: questionnaires).or(Admin::Answer.where(answerable: proposal))

    return attachments.or(Attachment.where(item: answers))
  end

  def set_default_members_only_text
    return if !has_attribute?(:members_only_text) || members_only_text.present?

    editable_block = Admin::EditableBlock.find_by(name: 'Event Members-Only Text Default')

    self.members_only_text = editable_block.present? ? editable_block.content : ''
  end

  def as_json(options = {})
    defaults = { methods: [:thumb_image_url, :slideshow_image_url], include: [:venue, { pictures: { methods: [:thumb_url, :display_url] } }, team_members: { methods: [:user_name] }] }

    options = merge_hash(defaults, options)

    super(options)
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::GenericEventsController
  def index
    @editable_block_name = 'Events Admin Description'
    @url = :admin_events

    super
  end
end

app/controllers/archives/events_controller.rb
class Archives::EventsController < Archives::GenericEventsController
  def index
    @url = :archives_events

    super
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def find_by_xts_id
    @event = Event.find_by_xts_id(params[:id])

    render json: @event.to_json(methods: [:slideshow_image_url], include: [pictures: { methods: [:display_url] }])
  end
end

app/views/admin/events/_basic_form.erb
<% # Looks for an input tagged with event_name and an input tagged with event_slug %>
<%= javascript_include_tag 'name_to_slug.js' %>

<%= f.input :name, input_html: { id: 'event_name' } %>

<%= f.input :tagline %>

<%= f.input :slug, input_html: { id: 'event_slug' } %>

<%= render 'shared/form/file_field', f: f, field_name: :image, hint: 'This is the image that appears in the slideshow on the frontpage, and as the header image on your event page. The apect ratio should be approximately 48/25.' %>

<%= f.input :start_date, start_year: Rails.configuration.start_year, end_year: max_end_year %>

<%= f.input :end_date, start_year: Rails.configuration.start_year, end_year: max_end_year %>

<%= f.association :venue, collection: Venue.all, label_method: :name %>

<%= f.input :author %>

<%= f.input :price %>

<% unless f.object.is_a? Season %>
  <% if f.object.persisted? %>
    <%= f.association :season, collection: f.object.simultaneous_seasons, label_method: :name %>
  <% else %>
    <p>You can add a season after adding the event.</p>
  <% end %>
<% end %>

<%= f.association :proposal, collection: f.object.possible_proposals, label_method: :show_title %>

<%= render '/shared/form/public_private_switch', f: f, field_symbol: :is_public %>

<%= render "/shared/form/md_editor", f: f, field: :publicity_text, show_hint: true %>

<%= render "/shared/form/md_editor", f: f, field: :members_only_text, show_hint: true %>

<%= render 'admin/events/event_tags_form_section', f: f %>

<%= render '/shared/form/sections/gallery', f: f %>

<%= render 'shared/form/sections/attachments', f: f %>

<%= render 'shared/form/sections/video_links', f: f %>

app/views/admin/events/_basic_show.erb
<% # I cannot guarantee that all of these if's are properly tested (all cases being hit), so be careful when modifying %>

<% # Note: If you update the ransack search form, this has some things with q that need to be changed. %>

<% fields = { 
  slug: event.slug,
  'ID' => (event.id if can?(:manage, event)),
  'SparkSeat Slug' => (event.spark_seat_slug if event.spark_seat_slug.present?),
  'XTS ID' => (event.xts_id if event.xts_id.present?),
  is_public: bool_text(event.is_public),
  proposal: 'No proposal linked',
  season: event.season.present? ? get_link(event.season, :show) : 'Not part of a season',
  author: event.author.present? ? link_to(event.author, admin_events_url('q[author_cont]' => event.author)) : 'No author specified',
  'Date(s)' => event.date_range(true),
  venue: event.venue.present? ? link_to(event.venue.name, admin_events_url('q[venue_id_eq]' => event.venue.id)) : 'No Venue specified',
  price: event.price,
  tagline: event.tagline.presence || 'No tagline',
  image: 'No image',
  event_tags: event.event_tags.accessible_by(current_ability).collect{ |event_tag| link_to(event_tag.name, admin_events_url('q[event_tags_id_eq]' => event_tag.id))}.join('; ').presence&.html_safe() || 'There are no tags set for this event.'
} %>

<% # Proposal %>
<% if event.proposal.present? && can?(:view, event.proposal) %>
  <% fields[:proposal] = get_link(event.proposal, :show, link_target: admin_proposals_proposal_path(event.proposal)) %>
<% end %>

<% # Image %>
<% if event.image.attached? && !event.image.filename.to_s.starts_with?(ActiveStorageHelper::PREFIX) %>
  <% fields[:image] = image_tag(event.fetch_image.variant(slideshow_variant)) %>
<% end %>

<%= render 'shared/basic_fields', fields: fields %>

<div class="row vertical-rule">
  <div class="span<%= event.team_members.any? ? '6' : '12' %>">
    <p>
      <h3>Publicity Text</h3>
      <%= render_markdown event.publicity_text %>
    </p>
  </div>

  <% if event.team_members.any? %>
    <div class="span6">
        <%= render '/shared/admin_show_team_members', team_members: event.team_members %>
    </div>
  <% end %>
</div>

<h3>Members-Only Text</h3>
<%= render_markdown event.members_only_text %>

app/views/admin/events/_event_tags_form_section.erb
<div class="form-horizontal">
  <h3>Tags</h3>

  <% no_event_tags = f.object.event_tags.empty? %>

  <% if no_event_tags %>
    <div id="no_event_tags_warning" class="alert alert-danger">
    You have not set any tags for this Event.
    </div>
  <% end %>

  <%= render layout: '/shared/collapsible_section', locals: { title: 'Tags', start_open: no_event_tags } do %>
    <% if f.object.errors[:event_tags].present? then %>
      <p id="event_tags_errors" class="alert alert-error">
        <%= f.error :event_tags %>
      </p>
    <% end %>

    <%= f.collection_check_boxes(:event_tag_ids, EventTag.accessible_by(current_ability), :id, ->(event_tag) { get_link event_tag, :show, link_text: event_tag.name, target: :blank }) do |checkbox| %>
      <%= checkbox.label { "#{checkbox.check_box}   #{checkbox.text}".html_safe } %>
    <% end %>
  <% end %>
</div>

app/views/admin/events/_questionnaires.erb
<% questionnaires = event.questionnaires.accessible_by(current_ability) %>

<% if questionnaires.any? { |questionnaire| can?(:show, questionnaire) } %>
    <h3>Questionnaires</h3>

    <table class="table">
      <tbody>
        <% questionnaires.each do |questionnaire| %>
            <tr>
              <%= get_link questionnaire, :answer, http_method: :get, html_class: '', append_name: true, wrap_tag: 'td' %>   

              <%= get_link questionnaire, :show, prefix: 'View', append_name: cannot?(:answer, questionnaire), 
                           html_class: ('btn' if can?(:answer, questionnaire)), wrap_tag: 'td' 
              %>

              <%= get_link questionnaire, :edit, wrap_tag: 'td' %>
            </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

<%= get_link Admin::Questionnaires::Questionnaire, :new, 
             html_class: (questionnaires.empty? ? 'btn' : 'btn btn-primary'), 
             link_target: new_admin_questionnaires_questionnaire_url(event_id: event.id), 
             additional_condition: event.end_date > Date.today 
%>

app/views/admin/events/index.html.erb
<h1><%= @title %></h1>

<%= display_block(@editable_block_name, true) %> 

<%= render '/events/search_form', url: @url %>

<table class="table">
    <tbody>
        <tr>
          <th>Name</th>
          <th>Dates</th>
          <th>Tagline</th>
          <% if can? :edit, Show %>
            <th></th>
          <% end %>
        </tr>

        <% @events.each do |event| %>
          <tr>
              <%= get_link event, :show, wrap_tag: 'td' %>

              <td><%= event.date_range true, :short %>
              <td><%= event.short_blurb %></td>

              <%= get_link event, :edit, wrap_tag: 'td' %>
          </tr>
        <% end %>
    </tbody>
</table>

<%= will_paginate(@events) %>

<%= (get_link @events.klass, :new) if @events.klass != Event %>