config/routes.rb
require 'silencer'

ChaosRails::Application.routes.draw do
  devise_for :users

  use_doorkeeper
  use_doorkeeper_openid_connect

  root to: 'static#home'

  match '*path', to: 'application#options', via: :options

  resources :shows,       only: [:index, :show]
  resources :workshops,   only: [:index, :show]
  resources :news,        only: [:index, :show]
  resources :venues,      only: [:index, :show]
  resources :seasons,     only: [:index, :show]

  resources :membership_activation_tokens, only: [] do
    member do
      get 'activate', to: 'membership_activation_tokens#activate'
      put 'submit', to: 'membership_activation_tokens#submit'
      patch 'submit', to: 'membership_activation_tokens#submit'
    end
  end

  resources :users, only: [:show] do
    collection do
      get 'current', to: 'users#current'
    end
  end

  get 'marketing_creatives/sign_up', to: 'admin/marketing_creatives/profiles#sign_up'

  COMPLAINTS_ALIASES.each do |path|
    get path, to: redirect('complaints/new')
  end

  resources :complaints, only: [:new, :create]

  get 'attachments/:slug(/:style)', to: 'attachments#file', as: 'attachment'

  namespace :admin do
    get '', to: 'dashboard#index'

    get 'resources', to: 'resources#page', as: :resources_index
    get 'resources/membership_checker', to: 'resources#membership_checker', as: :resources_membership_checker
    get 'resources/(*page)', to: 'resources#page', as: :resources

    get 'answer/:id/file', to: 'answers#get_file', as: :answer_get_file

    resources :events, only: [:index, :show] do
      member do
        get 'xts', to: 'events#find_by_xts_id'
      end
    end

    resources :shows do
      resources :feedbacks, except: [:show]

      collection do
        get 'query_xts'
      end

      member do
        post 'create_staffing_debts', to: 'shows#create_staffing_debts'
        post 'create_maintenance_debts', to: 'shows#create_maintenance_debts'
        get 'xts_report'
        post 'convert_to_season', to: 'shows#convert_to_season'
        post 'convert_to_workshop', to: 'shows#convert_to_workshop'
      end
    end

    resources :workshops

    resources :debt_notifications, only: [:index]

    resources :staffing_debts do
      member do
        put 'assign'
        put 'unassign'
      end
    end

    resources :maintenance_debts do
      member do
        put 'convert_to_staffing_debt'
      end
    end

    resources :debts

    resources :venues
    resources :seasons
    resources :news
    resources :fault_reports

    resources :event_tags
    resources :attachment_tags
    resources :picture_tags

    resources :attachments, only: [:index]
    resources :pictures, only: [:index]

    resources :opportunities do
      member do
        put 'approve'
        put 'reject'
      end
    end

    resources :membership, only: [] do
      collection do
        get 'check_membership', to: 'membership#check_membership'
      end
    end

    resources :editable_blocks
    resources :mass_mails

    resources :users do
      member do
        post 'reset_password'
      end

      collection do
        get  'autocomplete_list', constraints: { format: :json }
      end
    end

    resources :membership_activation_tokens, only: [:new] do
      collection do
        post 'create_activation', to: 'membership_activation_tokens#create_activation'
        post 'create_reactivation', to: 'membership_activation_tokens#create_reactivation'
      end
    end

    resources :roles do
      member do
        post 'add_user', to: 'roles#add_user'
        delete 'purge', to: 'roles#purge'
      end
    end

    get  '/permissions/grid', to: 'permissions#grid', as: :permissions
    post '/permissions/grid', to: 'permissions#update_grid', as: :update_permissions

    resources :techies do
      collection do
        get 'tree'
      end
    end

    get 'techie_families', to: 'techies#index'

    namespace :marketing_creatives do
      resources :profiles do
        collection do
          get 'sign_up', to: 'profiles#sign_up'
        end

        member do
          put 'approve'
          put 'reject'
        end
      end

      resources '', controller: 'categories', as: 'categories'
    end

    resources :staffing_templates

    resources :staffings do
      collection do
        get ':slug/grid', to: 'staffings#grid', format: :html, as: :grid
        get 'guidelines'
      end
    end

    match '/staffings/job/:id/sign_up_confirm', to: 'staffings#sign_up_confirm', via: [:get, :put], as: :sign_up_confirm
    put '/staffings/job/:id/sign_up', to: 'staffings#sign_up', as: :staffing_sign_up

    get '/proposals', to: redirect('/admin/proposals/calls')
    namespace :proposals do
      resources :calls do
        member do
          put 'archive'
        end

        resources :proposals, only: :index
      end

      resources :proposals, except: :index do
        member do
          put 'approve'
          put 'reject'
          put 'convert'
        end
      end

      get '/about', to: 'proposals#about'
      resources :call_question_templates
    end

    namespace :questionnaires do
      resources :questionnaires do
        member do
          get  'answer', to: 'questionnaires#answer'
          put 'answer', to: 'questionnaires#set_answers'
          patch 'answer', to: 'questionnaires#set_answers'
        end
      end

      resources :questionnaire_templates
    end

    resources :complaints, except: [:new, :create] do
      get 'new', to: redirect('/complaints/new')
    end

    get '/reports/', to: 'reports#index', as: 'reports'
    namespace 'reports' do
      %w(roles members newsletter_subscribers staffing).each do |action|
        put action, action: action, as: action
      end
    end

    namespace 'jobs' do
      %w(overview working pending failed remove retry).each do |action|
        get action, action: action, as:  action, controller: '/admin/job_control'
      end
    end

    namespace 'help' do
      %w(kramdown venue_location).each do |action|
        get action, action: action, as:  action, controller: '/admin/help'
      end
    end

    get 'committee', to: 'static#committee', as: :committee

    if Rails.env.test? || Rails.env.development?
      get 'dashboard/widget/:widget_name', to: 'dashboard#widget'
    end
  end

  get 'archives', to: 'archives#index', as: :archives_index
  namespace :archives do
    get 'events', to: 'events#index', as: :events
    get 'shows', to: 'shows#index', as: :shows
    get 'workshops', to: 'workshops#index', as: :workshops
    get 'proposals', to: 'proposals#index', as: :proposals
  end

  post 'markdown/preview', to: 'markdown#preview'

  get 'about', to: 'about#page', as: :about_index
  get 'about/(*page)', to: 'about#page', as: :about

  get 'get_involved', to: 'get_involved#page', as: :get_involved_index
  get 'get_involved/opportunities', to: 'get_involved#opportunities', as: :get_involved_opportunities
  get 'get_involved/(*page)', to: 'get_involved#page', as: :get_involved

  get 'youth', to: redirect('/getinvolved/youth_project')

  get 'welcomeweek', to: redirect('/welcome_week')
  get 'welcome_week/parapicnic_in_the_park', to: redirect('https://theatreparadok.co.uk/events/2021_09_parapicnic/')
  get 'welcome_week/catching_up', to: redirect('https://theatreparadok.co.uk/events/catching-up-fringe-show-performance-screening-for-welcome-week/')

  get 'welcome_week', to: redirect('get_involved/welcome_week')

  get '/:id', to: 'seasons#show', constraints: Constraints::ExistingSeason.new

  get '/*page', to: 'static#show', as: :static, constraints: lambda { |request|
    !request.path.starts_with?('/rails/active_storage') && !request.path.starts_with?('/assets')
  }

end

app/controllers/admin/techies_controller.rb
##
# Responsible for the techie family tree.
##
class Admin::TechiesController < AdminController
  include GenericController

  load_and_authorize_resource except: :tree

  def show
    super

    @coparents = @techie.children.flat_map(&:parents).uniq - [@techie]
  end

  def tree
    authorize! :index, Techie
    @title = 'Techie Family Tree'

    @q = Techie.ransack(params[:q])

    include_siblings_of_related = false
    amount_of_generations = 10

    @base_techie = @q.result(distinct: true)

    if @base_techie.size == 1
      @techies = @base_techie.first.get_relatives(amount_of_generations, include_siblings_of_related)
    else
      @techies = @base_techie.includes(:children, :parents)
    end
  end

  private

  def permitted_params
    [:name, children_attributes: [:id, :_destroy, :name], parents_attributes: [:id, :_destroy, :name]]
  end

  def order_args
    :name
  end

  def ransack_default_sorts
    ['name asc']
  end
end

app/views/admin/techies/_form.html.erb
<%= simple_nested_form_for [:admin, @techie] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>

    <h3>Parents</h3>
    
    <%= f.simple_fields_for :parents do |parent| %>
      <%= render 'relation_field', relation: parent %>
    <% end %>

    <%= link_to_add f, :parents %>

    <h3>Children</h3>

    <%= f.simple_fields_for :children do |child| %>
      <%= render 'relation_field', relation: child %>
    <% end %>

    <%= link_to_add f, :children %>

  </div>
  
  <%= render '/shared/form/form_actions', f: f %>
<% end %>

app/views/admin/techies/_relation_field.erb
<div class="control-group fields"> 
  <%= relation.input_field :id, collection: Techie.where.not(id: @techie.id) %>

  <%= link_to_remove relation %>
</div>

app/views/admin/techies/edit.html.erb
<h1><%= @title %></h1>

<%= render 'form' %>

app/views/admin/techies/index.html.erb
<h1><%= @title %></h1>

<p>
  <%= link_to tree_admin_techies_url, class: 'btn' do %>
    <i class="fa fa-bar-chart" aria-hidden=”true”></i> Tree
  <% end %>
</p>

<div class="row">
    <div class="span12">
        <%= search_form_for @q, builder: SimpleForm::FormBuilder, url: :admin_techies, html: { id: 'search', class: 'form-search form-inline'} do |f| %>
            <%= f.input_field :name_cont, placeholder: 'Name',  required: false %>
        <% end %>
    </div>
</div>

<table class="table">
  <tr>
    <%= content_tag :th, sort_link(@q, :name, 'Name') %>
    <% if can? :edit, Techie %>
      <th></th>
    <% end %>
  </tr>

  <% @techies.each do |techie| %>
    <tr>
      <%= get_link techie, :show, wrap_tag: 'td' %>

      <%= get_link techie, :edit, wrap_tag: 'td' %>
    </tr>
  <% end %>
</table>

<br />


<%= will_paginate(@techies) %>

<%= get_link Techie, :new %>

app/views/admin/techies/new.html.erb
<h1><%= @title %></h1>

<%= render 'form' %>

app/views/admin/techies/show.html.erb
<h1><%= @title%></h1>

<h3>Parents</h3>

<ul>
  <% @techie.parents.each do |parent| %>
    <li><%= get_link parent, :show %></li>
  <% end %>
</ul>

<h3>Children</h3>

<ul>
  <% @techie.children.each do |child| %>
    <li><%= get_link child, :show %></li>
  <% end %>
</ul>

<h3>Co-Parents</h3>
<ul>
  <% @coparents.each do |coparent| %>
    <li><%= get_link coparent, :show %></li>
  <% end %>
</ul>


<hr />

<%= render '/shared/show_actions', object: @techie %>

app/views/admin/techies/tree.erb
<h1><%= @title %></h1>

<div>
  <%= get_link Techie, :index, html_class: 'btn btn-primary' %>

  <%= get_link Techie, :new, html_class: 'btn' %>
</div>

<div class="row">
    <div class="span12">
        <%= search_form_for @q, builder: SimpleForm::FormBuilder, url: :tree_admin_techies, html: { id: 'search', class: 'form-search form-inline'} do |f| %>
            <%= f.select :id_eq, options_from_collection_for_select(Techie.all, "id", "name", @q.id_eq), include_blank: true %>

            <%= f.submit :Search, class: 'btn' %>
        <% end %>
    </div>
</div>

<div id="canvas" style="width: 940px; height: 1500px;"></div>
<script>
var g = new Graph();

var render = function(renderer, node) {
        /* the Raphael set is obligatory, containing all you want to display */
        var text = renderer.text(node.point[0] + 10, node.point[1] + 10, node.label);
        var dimensions = text.getBBox();

        var set = renderer.set().push(
            /* custom objects go here */
            renderer.rect(node.point[0] - (dimensions.width)/2, node.point[1], dimensions.width + 20, dimensions.height + 10).attr({"fill": "#feb", r : "12px", "stroke-width" : node.distance == 0 ? "3px" : "1px" })).push(
              text
            );

        text.toFront();
        return set;
    };

/* add a simple node */
<% @techies.each do |techie| %>
g.addNode("<%= techie.id %>", { render:render, label: "<%= techie.name.html_safe %>" });
<% end %>

<% @techies.each do |techie| %>
    <% techie.children.each do |child| %>
        <% if @techies.include?(child) %>
            g.addEdge("<%= techie.id %>", "<%= child.id %>", {directed: true});
        <% end %>
    <% end %>
<% end %>

/* layout the graph using the Spring layout implementation */
var layouter = new Graph.Layout.Spring(g);
layouter.layout();

/* draw the graph using the RaphaelJS draw implementation */
var renderer = new Graph.Renderer.Raphael('canvas', g, 940, 1500);
renderer.draw();
</script>